### ISSUE TITLE
Node mission types incorrect for Disruption

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [WFCD/warframe-status#92] opened 2019-09-03 09:22 UTC
The current arbitration up in-game is Disruption on Laomedeia. This API returns:

`"arbitration":{"activation":"2019-09-03T09:05:00.000Z","expiry":"2019-09-03T10:05:00.000Z","solnode":"SolNode118","node":"Laomedeia (Neptune)","name":"Laomedeia [Neptune]","tile":"Laomedeia","planet":"Neptune","enemy":"Corpus","type":"Spy","node_type":"NT_MISSION","archwing":false,"sharkwing":false}`

which is still using the old Spy mission type. I don't know on whose end this error is (I'd guess it might be DE since these new nodes are so new)

**Comment by Athari** [comment] 2019-09-22 05:14
Node information needs to be updated. This is what happens when node wasn't available previously:

`"arbitration":{"activation":"2019-09-22T05:05:00.000Z","expiry":"2019-09-22T06:05:00.000Z","solnode":"SolNode308","node":"undefined (undefined)"}`

`SolNode308` is Apollo (Lua), disruption.

**Comment by TobiTenno** [comment] 2019-09-23 21:35
Dupe of https://github.com/WFCD/warframe-worldstate-data/issues/129

**Closed by TobiTenno** 2019-09-23 21:35 UTC
